<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>cgr</AssemblyName>
    <VersionPrefix>0.0.1</VersionPrefix>
    <VersionSuffix>dev</VersionSuffix>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>cgr</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <PackageId>codex-github-router</PackageId>
  </PropertyGroup>

</Project>
